INSERT INTO move (name) VALUES ('Pound');
INSERT INTO move (name) VALUES ('Karate Chop');
INSERT INTO move (name) VALUES ('DoubleSlap');
INSERT INTO move (name) VALUES ('Comet Punch');
INSERT INTO move (name) VALUES ('Mega Punch');
INSERT INTO move (name) VALUES ('Pay Day');
INSERT INTO move (name) VALUES ('Fire Punch');
INSERT INTO move (name) VALUES ('Ice Punch');
INSERT INTO move (name) VALUES ('ThunderPunch');
INSERT INTO move (name) VALUES ('Scratch');
INSERT INTO move (name) VALUES ('ViceGrip');
INSERT INTO move (name) VALUES ('Guillotine');
INSERT INTO move (name) VALUES ('Razor Wind');
INSERT INTO move (name) VALUES ('Swords Dance');
INSERT INTO move (name) VALUES ('Cut');
INSERT INTO move (name) VALUES ('Gust');
INSERT INTO move (name) VALUES ('Wing Attack');
INSERT INTO move (name) VALUES ('Whirlwind');
INSERT INTO move (name) VALUES ('Fly');
INSERT INTO move (name) VALUES ('Bind');
INSERT INTO move (name) VALUES ('Slam');
INSERT INTO move (name) VALUES ('Vine Whip');
INSERT INTO move (name) VALUES ('Stomp');
INSERT INTO move (name) VALUES ('Double Kick');
INSERT INTO move (name) VALUES ('Mega Kick');
INSERT INTO move (name) VALUES ('Jump Kick');
INSERT INTO move (name) VALUES ('Rolling Kick');
INSERT INTO move (name) VALUES ('Sand-Attack');
INSERT INTO move (name) VALUES ('Headbutt');
INSERT INTO move (name) VALUES ('Horn Attack');
INSERT INTO move (name) VALUES ('Fury Attack');
INSERT INTO move (name) VALUES ('Horn Drill');
INSERT INTO move (name) VALUES ('Tackle');
INSERT INTO move (name) VALUES ('Body Slam');
INSERT INTO move (name) VALUES ('Wrap');
INSERT INTO move (name) VALUES ('Take Down');
INSERT INTO move (name) VALUES ('Thrash');
INSERT INTO move (name) VALUES ('Double-Edge');
INSERT INTO move (name) VALUES ('Tail Whip');
INSERT INTO move (name) VALUES ('Poison Sting');
INSERT INTO move (name) VALUES ('Twineedle');
INSERT INTO move (name) VALUES ('Pin Missile');
INSERT INTO move (name) VALUES ('Leer');
INSERT INTO move (name) VALUES ('Bite');
INSERT INTO move (name) VALUES ('Growl');
INSERT INTO move (name) VALUES ('Roar');
INSERT INTO move (name) VALUES ('Sing');
INSERT INTO move (name) VALUES ('Supersonic');
INSERT INTO move (name) VALUES ('SonicBoom');
INSERT INTO move (name) VALUES ('Disable');
INSERT INTO move (name) VALUES ('Acid');
INSERT INTO move (name) VALUES ('Ember');
INSERT INTO move (name) VALUES ('Flamethrower');
INSERT INTO move (name) VALUES ('Mist');
INSERT INTO move (name) VALUES ('Water Gun');
INSERT INTO move (name) VALUES ('Hydro Pump');
INSERT INTO move (name) VALUES ('Surf');
INSERT INTO move (name) VALUES ('Ice Beam');
INSERT INTO move (name) VALUES ('Blizzard');
INSERT INTO move (name) VALUES ('Psybeam');
INSERT INTO move (name) VALUES ('BubbleBeam');
INSERT INTO move (name) VALUES ('Aurora Beam');
INSERT INTO move (name) VALUES ('Hyper Beam');
INSERT INTO move (name) VALUES ('Peck');
INSERT INTO move (name) VALUES ('Drill Peck');
INSERT INTO move (name) VALUES ('Submission');
INSERT INTO move (name) VALUES ('Low Kick');
INSERT INTO move (name) VALUES ('Counter');
INSERT INTO move (name) VALUES ('Seismic Toss');
INSERT INTO move (name) VALUES ('Strength');
INSERT INTO move (name) VALUES ('Absorb');
INSERT INTO move (name) VALUES ('Mega Drain');
INSERT INTO move (name) VALUES ('Leech Seed');
INSERT INTO move (name) VALUES ('Growth');
INSERT INTO move (name) VALUES ('Razor Leaf');
INSERT INTO move (name) VALUES ('SolarBeam');
INSERT INTO move (name) VALUES ('PoisonPowder');
INSERT INTO move (name) VALUES ('Stun Spore');
INSERT INTO move (name) VALUES ('Sleep Powder');
INSERT INTO move (name) VALUES ('Petal Dance');
INSERT INTO move (name) VALUES ('String Shot');
INSERT INTO move (name) VALUES ('Dragon Rage');
INSERT INTO move (name) VALUES ('Fire Spin');
INSERT INTO move (name) VALUES ('ThunderShock');
INSERT INTO move (name) VALUES ('Thunderbolt');
INSERT INTO move (name) VALUES ('Thunder Wave');
INSERT INTO move (name) VALUES ('Thunder');
INSERT INTO move (name) VALUES ('Rock Throw');
INSERT INTO move (name) VALUES ('Earthquake');
INSERT INTO move (name) VALUES ('Fissure');
INSERT INTO move (name) VALUES ('Dig');
INSERT INTO move (name) VALUES ('Toxic');
INSERT INTO move (name) VALUES ('Confusion');
INSERT INTO move (name) VALUES ('Psychic');
INSERT INTO move (name) VALUES ('Hypnosis');
INSERT INTO move (name) VALUES ('Meditate');
INSERT INTO move (name) VALUES ('Agility');
INSERT INTO move (name) VALUES ('Quick Attack');
INSERT INTO move (name) VALUES ('Rage');
INSERT INTO move (name) VALUES ('Teleport');
INSERT INTO move (name) VALUES ('Night Shade');
INSERT INTO move (name) VALUES ('Mimic');
INSERT INTO move (name) VALUES ('Screech');
INSERT INTO move (name) VALUES ('Double Team');
INSERT INTO move (name) VALUES ('Recover');
INSERT INTO move (name) VALUES ('Harden');
INSERT INTO move (name) VALUES ('Minimize');
INSERT INTO move (name) VALUES ('SmokeScreen');
INSERT INTO move (name) VALUES ('Confuse Ray');
INSERT INTO move (name) VALUES ('Withdraw');
INSERT INTO move (name) VALUES ('Defense Curl');
INSERT INTO move (name) VALUES ('Barrier');
INSERT INTO move (name) VALUES ('Light Screen');
INSERT INTO move (name) VALUES ('Haze');
INSERT INTO move (name) VALUES ('Reflect');
INSERT INTO move (name) VALUES ('Focus Energy');
INSERT INTO move (name) VALUES ('Bide');
INSERT INTO move (name) VALUES ('Metronome');
INSERT INTO move (name) VALUES ('Mirror Move');
INSERT INTO move (name) VALUES ('Selfdestruct');
INSERT INTO move (name) VALUES ('Egg Bomb');
INSERT INTO move (name) VALUES ('Lick');
INSERT INTO move (name) VALUES ('Smog');
INSERT INTO move (name) VALUES ('Sludge');
INSERT INTO move (name) VALUES ('Bone Club');
INSERT INTO move (name) VALUES ('Fire Blast');
INSERT INTO move (name) VALUES ('Waterfall');
INSERT INTO move (name) VALUES ('Clamp');
INSERT INTO move (name) VALUES ('Swift');
INSERT INTO move (name) VALUES ('Skull Bash');
INSERT INTO move (name) VALUES ('Spike Cannon');
INSERT INTO move (name) VALUES ('Constrict');
INSERT INTO move (name) VALUES ('Amnesia');
INSERT INTO move (name) VALUES ('Kinesis');
INSERT INTO move (name) VALUES ('Softboiled');
INSERT INTO move (name) VALUES ('Hi Jump Kick');
INSERT INTO move (name) VALUES ('Glare');
INSERT INTO move (name) VALUES ('Dream Eater');
INSERT INTO move (name) VALUES ('Poison Gas');
INSERT INTO move (name) VALUES ('Barrage');
INSERT INTO move (name) VALUES ('Leech Life');
INSERT INTO move (name) VALUES ('Lovely Kiss');
INSERT INTO move (name) VALUES ('Sky Attack');
INSERT INTO move (name) VALUES ('Transform');
INSERT INTO move (name) VALUES ('Bubble');
INSERT INTO move (name) VALUES ('Dizzy Punch');
INSERT INTO move (name) VALUES ('Spore');
INSERT INTO move (name) VALUES ('Flash');
INSERT INTO move (name) VALUES ('Psywave');
INSERT INTO move (name) VALUES ('Splash');
INSERT INTO move (name) VALUES ('Acid Armor');
INSERT INTO move (name) VALUES ('Crabhammer');
INSERT INTO move (name) VALUES ('Explosion');
INSERT INTO move (name) VALUES ('Fury Swipes');
INSERT INTO move (name) VALUES ('Bonemerang');
INSERT INTO move (name) VALUES ('Rest');
INSERT INTO move (name) VALUES ('Rock Slide');
INSERT INTO move (name) VALUES ('Hyper Fang');
INSERT INTO move (name) VALUES ('Sharpen');
INSERT INTO move (name) VALUES ('Conversion');
INSERT INTO move (name) VALUES ('Tri Attack');
INSERT INTO move (name) VALUES ('Super Fang');
INSERT INTO move (name) VALUES ('Slash');
INSERT INTO move (name) VALUES ('Substitute');
INSERT INTO move (name) VALUES ('Struggle');
INSERT INTO move (name) VALUES ('Sketch');
INSERT INTO move (name) VALUES ('Triple Kick');
INSERT INTO move (name) VALUES ('Thief');
INSERT INTO move (name) VALUES ('Spider Web');
INSERT INTO move (name) VALUES ('Mind Reader');
INSERT INTO move (name) VALUES ('Nightmare');
INSERT INTO move (name) VALUES ('Flame Wheel');
INSERT INTO move (name) VALUES ('Snore');
INSERT INTO move (name) VALUES ('Curse');
INSERT INTO move (name) VALUES ('Flail');
INSERT INTO move (name) VALUES ('Conversion 2');
INSERT INTO move (name) VALUES ('Aeroblast');
INSERT INTO move (name) VALUES ('Cotton Spore');
INSERT INTO move (name) VALUES ('Reversal');
INSERT INTO move (name) VALUES ('Spite');
INSERT INTO move (name) VALUES ('Powder Snow');
INSERT INTO move (name) VALUES ('Protect');
INSERT INTO move (name) VALUES ('Mach Punch');
INSERT INTO move (name) VALUES ('Scary Face');
INSERT INTO move (name) VALUES ('Faint Attack');
INSERT INTO move (name) VALUES ('Sweet Kiss');
INSERT INTO move (name) VALUES ('Belly Drum');
INSERT INTO move (name) VALUES ('Sludge Bomb');
INSERT INTO move (name) VALUES ('Mud-Slap');
INSERT INTO move (name) VALUES ('Octazooka');
INSERT INTO move (name) VALUES ('Spikes');
INSERT INTO move (name) VALUES ('Zap Cannon');
INSERT INTO move (name) VALUES ('Foresight');
INSERT INTO move (name) VALUES ('Destiny Bond');
INSERT INTO move (name) VALUES ('Perish Song');
INSERT INTO move (name) VALUES ('Icy Wind');
INSERT INTO move (name) VALUES ('Detect');
INSERT INTO move (name) VALUES ('Bone Rush');
INSERT INTO move (name) VALUES ('Lock-On');
INSERT INTO move (name) VALUES ('Outrage');
INSERT INTO move (name) VALUES ('Sandstorm');
INSERT INTO move (name) VALUES ('Giga Drain');
INSERT INTO move (name) VALUES ('Endure');
INSERT INTO move (name) VALUES ('Charm');
INSERT INTO move (name) VALUES ('Rollout');
INSERT INTO move (name) VALUES ('False Swipe');
INSERT INTO move (name) VALUES ('Swagger');
INSERT INTO move (name) VALUES ('Milk Drink');
INSERT INTO move (name) VALUES ('Spark');
INSERT INTO move (name) VALUES ('Fury Cutter');
INSERT INTO move (name) VALUES ('Steel Wing');
INSERT INTO move (name) VALUES ('Mean Look');
INSERT INTO move (name) VALUES ('Attract');
INSERT INTO move (name) VALUES ('Sleep Talk');
INSERT INTO move (name) VALUES ('Heal Bell');
INSERT INTO move (name) VALUES ('Return');
INSERT INTO move (name) VALUES ('Present');
INSERT INTO move (name) VALUES ('Frustration');
INSERT INTO move (name) VALUES ('Safeguard');
INSERT INTO move (name) VALUES ('Pain Split');
INSERT INTO move (name) VALUES ('Sacred Fire');
INSERT INTO move (name) VALUES ('Magnitude');
INSERT INTO move (name) VALUES ('DynamicPunch');
INSERT INTO move (name) VALUES ('Megahorn');
INSERT INTO move (name) VALUES ('DragonBreath');
INSERT INTO move (name) VALUES ('Baton Pass');
INSERT INTO move (name) VALUES ('Encore');
INSERT INTO move (name) VALUES ('Pursuit');
INSERT INTO move (name) VALUES ('Rapid Spin');
INSERT INTO move (name) VALUES ('Sweet Scent');
INSERT INTO move (name) VALUES ('Iron Tail');
INSERT INTO move (name) VALUES ('Metal Claw');
INSERT INTO move (name) VALUES ('Vital Throw');
INSERT INTO move (name) VALUES ('Morning Sun');
INSERT INTO move (name) VALUES ('Synthesis');
INSERT INTO move (name) VALUES ('Moonlight');
INSERT INTO move (name) VALUES ('Hidden Power');
INSERT INTO move (name) VALUES ('Cross Chop');
INSERT INTO move (name) VALUES ('Twister');
INSERT INTO move (name) VALUES ('Rain Dance');
INSERT INTO move (name) VALUES ('Sunny Day');
INSERT INTO move (name) VALUES ('Crunch');
INSERT INTO move (name) VALUES ('Mirror Coat');
INSERT INTO move (name) VALUES ('Psych Up');
INSERT INTO move (name) VALUES ('ExtremeSpeed');
INSERT INTO move (name) VALUES ('AncientPower');
INSERT INTO move (name) VALUES ('Shadow Ball');
INSERT INTO move (name) VALUES ('Future Sight');
INSERT INTO move (name) VALUES ('Rock Smash');
INSERT INTO move (name) VALUES ('Whirlpool');
INSERT INTO move (name) VALUES ('Beat Up');
INSERT INTO move (name) VALUES ('Fake Out');
INSERT INTO move (name) VALUES ('Uproar');
INSERT INTO move (name) VALUES ('Stockpile');
INSERT INTO move (name) VALUES ('Spit Up');
INSERT INTO move (name) VALUES ('Swallow');
INSERT INTO move (name) VALUES ('Heat Wave');
INSERT INTO move (name) VALUES ('Hail');
INSERT INTO move (name) VALUES ('Torment');
INSERT INTO move (name) VALUES ('Flatter');
INSERT INTO move (name) VALUES ('Will-O-Wisp');
INSERT INTO move (name) VALUES ('Memento');
INSERT INTO move (name) VALUES ('Facade');
INSERT INTO move (name) VALUES ('Focus Punch');
INSERT INTO move (name) VALUES ('SmellingSalt');
INSERT INTO move (name) VALUES ('Follow Me');
INSERT INTO move (name) VALUES ('Nature Power');
INSERT INTO move (name) VALUES ('Nature Power (Wifi)');
INSERT INTO move (name) VALUES ('Charge');
INSERT INTO move (name) VALUES ('Taunt');
INSERT INTO move (name) VALUES ('Helping Hand');
INSERT INTO move (name) VALUES ('Trick');
INSERT INTO move (name) VALUES ('Role Play');
INSERT INTO move (name) VALUES ('Wish');
INSERT INTO move (name) VALUES ('Assist');
INSERT INTO move (name) VALUES ('Ingrain');
INSERT INTO move (name) VALUES ('Superpower');
INSERT INTO move (name) VALUES ('Magic Coat');
INSERT INTO move (name) VALUES ('Recycle');
INSERT INTO move (name) VALUES ('Revenge');
INSERT INTO move (name) VALUES ('Brick Break');
INSERT INTO move (name) VALUES ('Yawn');
INSERT INTO move (name) VALUES ('Knock Off');
INSERT INTO move (name) VALUES ('Endeavor');
INSERT INTO move (name) VALUES ('Eruption');
INSERT INTO move (name) VALUES ('Skill Swap');
INSERT INTO move (name) VALUES ('Imprison');
INSERT INTO move (name) VALUES ('Refresh');
INSERT INTO move (name) VALUES ('Grudge');
INSERT INTO move (name) VALUES ('Snatch');
INSERT INTO move (name) VALUES ('Secret Power');
INSERT INTO move (name) VALUES ('Dive');
INSERT INTO move (name) VALUES ('Arm Thrust');
INSERT INTO move (name) VALUES ('Camouflage');
INSERT INTO move (name) VALUES ('Tail Glow');
INSERT INTO move (name) VALUES ('Luster Purge');
INSERT INTO move (name) VALUES ('Mist Ball');
INSERT INTO move (name) VALUES ('FeatherDance');
INSERT INTO move (name) VALUES ('Teeter Dance');
INSERT INTO move (name) VALUES ('Blaze Kick');
INSERT INTO move (name) VALUES ('Mud Sport');
INSERT INTO move (name) VALUES ('Ice Ball');
INSERT INTO move (name) VALUES ('Needle Arm');
INSERT INTO move (name) VALUES ('Slack Off');
INSERT INTO move (name) VALUES ('Hyper Voice');
INSERT INTO move (name) VALUES ('Poison Fang');
INSERT INTO move (name) VALUES ('Crush Claw');
INSERT INTO move (name) VALUES ('Blast Burn');
INSERT INTO move (name) VALUES ('Hydro Cannon');
INSERT INTO move (name) VALUES ('Meteor Mash');
INSERT INTO move (name) VALUES ('Astonish');
INSERT INTO move (name) VALUES ('Weather Ball');
INSERT INTO move (name) VALUES ('Aromatherapy');
INSERT INTO move (name) VALUES ('Fake Tears');
INSERT INTO move (name) VALUES ('Air Cutter');
INSERT INTO move (name) VALUES ('Overheat');
INSERT INTO move (name) VALUES ('Odor Sleuth');
INSERT INTO move (name) VALUES ('Rock Tomb');
INSERT INTO move (name) VALUES ('Silver Wind');
INSERT INTO move (name) VALUES ('Metal Sound');
INSERT INTO move (name) VALUES ('GrassWhistle');
INSERT INTO move (name) VALUES ('Tickle');
INSERT INTO move (name) VALUES ('Cosmic Power');
INSERT INTO move (name) VALUES ('Water Spout');
INSERT INTO move (name) VALUES ('Signal Beam');
INSERT INTO move (name) VALUES ('Shadow Punch');
INSERT INTO move (name) VALUES ('Extrasensory');
INSERT INTO move (name) VALUES ('Sky Uppercut');
INSERT INTO move (name) VALUES ('Sand Tomb');
INSERT INTO move (name) VALUES ('Sheer Cold');
INSERT INTO move (name) VALUES ('Muddy Water');
INSERT INTO move (name) VALUES ('Bullet Seed');
INSERT INTO move (name) VALUES ('Aerial Ace');
INSERT INTO move (name) VALUES ('Icicle Spear');
INSERT INTO move (name) VALUES ('Iron Defense');
INSERT INTO move (name) VALUES ('Block');
INSERT INTO move (name) VALUES ('Howl');
INSERT INTO move (name) VALUES ('Dragon Claw');
INSERT INTO move (name) VALUES ('Frenzy Plant');
INSERT INTO move (name) VALUES ('Bulk Up');
INSERT INTO move (name) VALUES ('Bounce');
INSERT INTO move (name) VALUES ('Mud Shot');
INSERT INTO move (name) VALUES ('Poison Tail');
INSERT INTO move (name) VALUES ('Covet');
INSERT INTO move (name) VALUES ('Volt Tackle');
INSERT INTO move (name) VALUES ('Magical Leaf');
INSERT INTO move (name) VALUES ('Water Sport');
INSERT INTO move (name) VALUES ('Calm Mind');
INSERT INTO move (name) VALUES ('Leaf Blade');
INSERT INTO move (name) VALUES ('Dragon Dance');
INSERT INTO move (name) VALUES ('Rock Blast');
INSERT INTO move (name) VALUES ('Shock Wave');
INSERT INTO move (name) VALUES ('Water Pulse');
INSERT INTO move (name) VALUES ('Doom Desire');
INSERT INTO move (name) VALUES ('Psycho Boost');




INSERT INTO type (name) VALUES ('Normal');
INSERT INTO type (name) VALUES ('Fire');
INSERT INTO type (name) VALUES ('Water');
INSERT INTO type (name) VALUES ('Grass');
INSERT INTO type (name) VALUES ('Eletric');
INSERT INTO type (name) VALUES ('Ice');
INSERT INTO type (name) VALUES ('Fighting');
INSERT INTO type (name) VALUES ('Poison');
INSERT INTO type (name) VALUES ('Ground');
INSERT INTO type (name) VALUES ('Flying');
INSERT INTO type (name) VALUES ('Psychic');
INSERT INTO type (name) VALUES ('Bug');
INSERT INTO type (name) VALUES ('Rock');
INSERT INTO type (name) VALUES ('Ghost');
INSERT INTO type (name) VALUES ('Dark');
INSERT INTO type (name) VALUES ('Dragon');
INSERT INTO type (name) VALUES ('Steel');
INSERT INTO type (name) VALUES ('Fairy');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '1', 'Aegiochusmon', 'https://wikimon.net/images/thumb/b/bd/Aegiochusmon.jpg/120px-Aegiochusmon.jpg', '150', '14', null);
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('906', '97');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('906', '176');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('906', '279');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '1', 'Aegiochusmon: Blue', 'https://wikimon.net/images/thumb/b/bb/Aegiochusmon_blue2.jpg/120px-Aegiochusmon_blue2.jpg', '42', '3', '16');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('907', '53');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('907', '232');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('907', '194');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '1', 'Aegiochusmon: Dark', 'https://wikimon.net/images/thumb/7/7a/Aegiochusmon_dark.jpg/120px-Aegiochusmon_dark.jpg', '54', '3', null);
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('908', '22');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('908', '88');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('908', '308');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('908', '43');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('908', '316');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('908', '279');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('908', '160');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '5', 'Aegiochusmon: Green', 'https://wikimon.net/images/thumb/d/d4/Aegiochusmon_green.jpg/120px-Aegiochusmon_green.jpg', '145', '4', null);
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('909', '64');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('909', '52');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('909', '321');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('909', '10');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('909', '253');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('909', '69');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('909', '348');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '3', 'Aegiochusmon: Holy', 'https://wikimon.net/images/thumb/0/0b/Aegiochusmon_holly.jpg/120px-Aegiochusmon_holly.jpg', '53', '10', null);
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('910', '230');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('910', '180');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('910', '315');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '3', 'Aegiomon', 'https://wikimon.net/images/thumb/9/98/Aegiomon2.jpg/120px-Aegiomon2.jpg', '41', '4', null);
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('911', '216');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('911', '5');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('911', '56');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '2', 'Aegisdramon', 'https://wikimon.net/images/thumb/8/83/Ageisdramon.jpg/120px-Ageisdramon.jpg', '127', '4', null);
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('912', '57');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('912', '13');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '4', 'Aero V-dramon', 'https://wikimon.net/images/thumb/5/54/Aerovdramon.jpg/120px-Aerovdramon.jpg', '111', '13', null);
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('913', '141');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('913', '20');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('913', '75');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '3', 'Agnimon', 'https://wikimon.net/images/thumb/d/dc/Agnimon3.jpg/120px-Agnimon3.jpg', '123', '7', null);
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('914', '239');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('914', '290');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('914', '95');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('914', '118');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '5', 'Agumon', 'https://wikimon.net/images/thumb/7/72/Agumon.jpg/120px-Agumon.jpg', '126', '18', '4');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('915', '195');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('915', '41');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('915', '49');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('915', '202');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '2', 'Agumon X-Antibody', 'https://wikimon.net/images/thumb/3/30/Agumonx2.jpg/120px-Agumonx2.jpg', '143', '14', null);
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('916', '149');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('916', '251');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('916', '20');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('916', '85');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('916', '292');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('916', '295');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '5', 'Agumon (2006 Anime Version)', 'https://wikimon.net/images/thumb/8/80/Agumon2.jpg/120px-Agumon2.jpg', '89', '16', null);
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('917', '296');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('917', '355');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '4', 'Agumon (Black)', 'https://wikimon.net/images/thumb/9/91/Agumon_black.jpg/120px-Agumon_black.jpg', '133', '10', '18');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('918', '166');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('918', '326');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('918', '252');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('918', '91');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('918', '43');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('918', '86');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '2', 'Agumon (Black) (2006 Anime Version)', 'https://wikimon.net/images/thumb/9/97/Agumon_black_2006.jpg/120px-Agumon_black_2006.jpg', '137', '15', '7');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('919', '301');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('919', '335');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('919', '260');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('919', '294');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '4', 'Agumon Burst Mode', 'https://wikimon.net/images/thumb/2/2a/Agumon_burst.jpg/120px-Agumon_burst.jpg', '149', '17', '13');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('920', '143');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('920', '47');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '5', 'Agumon Hakase', 'https://wikimon.net/images/thumb/1/1a/Agumon_hakase.jpg/120px-Agumon_hakase.jpg', '81', '3', null);
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('921', '208');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '3', 'Aircraft Carrier Whamon', 'https://wikimon.net/images/thumb/4/47/Aircraft_carrier_whamon.png/120px-Aircraft_carrier_whamon.png', '36', '1', null);
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('922', '148');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '3', 'Airdramon', 'https://wikimon.net/images/thumb/6/63/Airdramon.jpg/120px-Airdramon.jpg', '150', '2', '1');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('923', '23');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('923', '256');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('923', '204');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('923', '211');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('923', '288');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('923', '199');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('923', '196');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '3', 'Akatorimon', 'https://wikimon.net/images/thumb/d/df/Akatorimon.jpg/120px-Akatorimon.jpg', '125', '3', '5');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('924', '67');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('924', '344');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('924', '138');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('924', '167');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('924', '240');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('924', '244');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '1', 'Aldamon', 'https://wikimon.net/images/thumb/3/3b/Aldamon.jpg/120px-Aldamon.jpg', '118', '14', '15');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('925', '298');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('925', '70');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('925', '135');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('925', '334');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('925', '50');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('925', '253');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '5', 'Algomon', 'https://wikimon.net/images/thumb/d/d6/Algomon.jpg/120px-Algomon.jpg', '102', '12', null);
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('926', '225');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '3', 'Algomon Ultimate', 'https://wikimon.net/images/thumb/3/36/Algomon_ultimate.jpg/120px-Algomon_ultimate.jpg', '117', '9', null);
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('927', '150');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '5', 'Allomon', 'https://wikimon.net/images/thumb/5/5c/Allomon.jpg/120px-Allomon.jpg', '123', '9', '3');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('928', '133');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('928', '216');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('928', '204');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('928', '250');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('928', '284');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '2', 'Allomon X-Antibody', 'https://wikimon.net/images/thumb/7/77/Allomonx.jpg/120px-Allomonx.jpg', '67', '18', null);
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('929', '72');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('929', '173');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('929', '183');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('929', '244');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('929', '86');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('929', '209');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '3', 'Alphamon', 'https://wikimon.net/images/thumb/2/29/Alphamon.jpg/120px-Alphamon.jpg', '89', '7', '15');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('930', '17');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('930', '294');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('930', '215');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('930', '87');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '4', 'Alphamon Ouryuken', 'https://wikimon.net/images/thumb/3/39/Alphamon_ouryuken.jpg/120px-Alphamon_ouryuken.jpg', '113', '9', '13');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('931', '243');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('931', '285');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('931', '6');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('931', '73');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('931', '79');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('931', '184');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('931', '277');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '5', 'Alraumon', 'https://wikimon.net/images/thumb/3/3e/Alraumon.jpg/120px-Alraumon.jpg', '34', '6', null);
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('932', '160');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('932', '104');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '2', 'Amon', 'https://wikimon.net/images/thumb/f/f0/Amon.jpg/120px-Amon.jpg', '66', '9', '11');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('933', '110');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '5', 'Ancient Beatmon', 'https://wikimon.net/images/thumb/d/da/Ancientbeatmon.jpg/120px-Ancientbeatmon.jpg', '136', '15', '5');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('934', '49');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('934', '352');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('934', '299');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('934', '224');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('934', '1');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('934', '55');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('934', '319');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '5', 'Ancient Garurumon', 'https://wikimon.net/images/thumb/b/be/Ancientgarurumon.jpg/120px-Ancientgarurumon.jpg', '117', '18', null);
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('935', '349');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('935', '22');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('935', '94');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('935', '355');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('935', '235');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('935', '44');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '1', 'Ancient Greymon', 'https://wikimon.net/images/thumb/4/4e/Ancientgreymon.jpg/120px-Ancientgreymon.jpg', '53', '3', null);
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('936', '336');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('936', '292');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('936', '59');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('936', '308');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('936', '236');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('936', '239');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '4', 'Ancient Irismon', 'https://wikimon.net/images/thumb/a/a7/Ancientirismon.jpg/120px-Ancientirismon.jpg', '144', '7', '13');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('937', '156');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('937', '291');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '5', 'Ancient Megatheriumon', 'https://wikimon.net/images/thumb/4/4e/Ancientmegatheriumon.jpg/120px-Ancientmegatheriumon.jpg', '59', '6', '5');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('938', '268');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('938', '89');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('938', '347');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('938', '97');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('938', '266');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('938', '140');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '1', 'Ancient Mermaimon', 'https://wikimon.net/images/thumb/e/ec/Ancientmermaimon.jpg/120px-Ancientmermaimon.jpg', '139', '3', null);
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('939', '295');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('939', '338');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('939', '254');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('939', '335');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('939', '90');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('939', '22');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('939', '85');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '4', 'Ancient Sphinxmon', 'https://wikimon.net/images/thumb/8/84/Ancientsphinxmon.jpg/120px-Ancientsphinxmon.jpg', '118', '12', null);
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('940', '118');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '3', 'Ancient Troiamon', 'https://wikimon.net/images/thumb/6/61/Ancienttroiamon.jpg/120px-Ancienttroiamon.jpg', '55', '13', null);
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('941', '299');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('941', '19');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('941', '101');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '1', 'Ancient Volcamon', 'https://wikimon.net/images/thumb/c/c5/Ancientvolcamon.jpg/120px-Ancientvolcamon.jpg', '43', '13', '2');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('942', '47');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('942', '243');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('942', '122');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '4', 'Ancient Wisemon', 'https://wikimon.net/images/thumb/3/3c/Ancientwisemon.jpg/120px-Ancientwisemon.jpg', '70', '14', null);
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('943', '274');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('943', '88');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('943', '78');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('943', '173');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('943', '102');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '1', 'Andiramon', 'https://wikimon.net/images/thumb/4/41/Andiramon.jpg/120px-Andiramon.jpg', '96', '6', '18');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('944', '199');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('944', '100');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('944', '218');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('944', '67');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('944', '83');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '4', 'Andiramon (Deva)', 'https://wikimon.net/images/thumb/b/b8/Andiramon_data.jpg/120px-Andiramon_data.jpg', '91', '12', null);
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('945', '136');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('945', '65');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('945', '319');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('945', '39');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '1', 'Andromon', 'https://wikimon.net/images/thumb/1/10/Andromon.jpg/120px-Andromon.jpg', '86', '4', null);
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('946', '109');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('946', '19');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '1', 'Angemon', 'https://wikimon.net/images/thumb/1/1b/Angemon.jpg/120px-Angemon.jpg', '100', '11', null);
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('947', '204');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('947', '34');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('947', '160');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('947', '307');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('947', '133');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '4', 'Angewomon', 'https://wikimon.net/images/thumb/5/5a/Angewomon.jpg/120px-Angewomon.jpg', '97', '7', null);
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('948', '243');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '2', 'Ankylomon', 'https://wikimon.net/images/thumb/e/e0/Ankylomon2.jpg/120px-Ankylomon2.jpg', '74', '15', null);
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('949', '274');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('949', '32');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('949', '255');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('949', '282');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('949', '313');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '3', 'Anomalocarimon', 'https://wikimon.net/images/thumb/3/33/Anomalocarimon.jpg/120px-Anomalocarimon.jpg', '67', '9', '8');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('950', '67');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('950', '154');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('950', '110');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('950', '30');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '1', 'Anomalocarimon X-Antibody', 'https://wikimon.net/images/thumb/9/96/Anomalocarimonx.jpg/120px-Anomalocarimonx.jpg', '45', '15', null);
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('951', '66');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('951', '271');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('951', '20');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('951', '231');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '3', 'Anubimon', 'https://wikimon.net/images/thumb/c/c3/Anubimon.jpg/120px-Anubimon.jpg', '69', '9', '8');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('952', '33');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('952', '48');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('952', '224');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('952', '222');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('952', '232');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('952', '94');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('952', '116');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '5', 'Apocalymon', 'https://wikimon.net/images/thumb/4/48/Apocalymon3.jpg/120px-Apocalymon3.jpg', '33', '1', null);
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('953', '170');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('953', '338');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('953', '211');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('953', '192');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('953', '115');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '4', 'Apollomon', 'https://wikimon.net/images/thumb/d/d7/Apollomon.jpg/120px-Apollomon.jpg', '42', '18', '13');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('954', '239');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('954', '181');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('954', '98');

INSERT INTO pokemon (id, height, name, sprite, weight, type1_id, type2_id) VALUES (nextval('POKEMON_SEQ'), '3', 'Apollomon Darkness Mode', 'https://wikimon.net/images/thumb/9/96/Apollomon_darkness.jpg/120px-Apollomon_darkness.jpg', '138', '18', '17');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('955', '307');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('955', '228');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('955', '18');
INSERT INTO pokemon_moves (id_pokemon, id_move) VALUES ('955', '202');

